# Generated by Django 4.2.4 on 2023-08-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_task',
            name='date',
            field=models.DateField(default='2000-12-20'),
            preserve_default=False,
        ),
    ]
